services:
  - type: web
    plan: starter
    runtime: python
    name: public-testing
    buildCommand: ./render-build.sh
    startCommand: ./render-start.sh
    envVars:
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: public-testing-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: public-testing-redis
          type: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: BRIDGE_PLATFORM
        value: render
  - type: redis
    name: public-testing-redis
    plan: free
    ipAllowList: []

databases:
  - name: public-testing-db
    plan: free
    databaseName: public_testing_db
    user: public_testing
